### ISSUE TITLE
exception caused by certain chars in data 

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/dataquality#14] opened 2021-11-19 17:23 UTC
```
ERROR 2021-11-19 17:22:01,118 log 434081 140596001613696 Internal Server Error: /data/d56d1537-d1b0-4a35-b019-bcf46990245f
Traceback (most recent call last):
  File "/home/cove/dataquality/.ve/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/cove/dataquality/.ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/cove/dataquality/.ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cove/dataquality/.ve/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/cove/dataquality/.ve/lib/python3.8/site-packages/cove/views.py", line 23, in wrapper
    return func(request, *args, **kwargs)
  File "/home/cove/dataquality/cove/./cove_360/views.py", line 73, in explore_360
    context = common_checks_360(context, upload_dir, json_data, schema_360)
  File "/home/cove/dataquality/lib360dataquality/cove/threesixtygiving.py", line 340, in common_checks_360
    common_checks = common_checks_context(
  File "/home/cove/dataquality/.ve/lib/python3.8/site-packages/libcove/lib/common.py", line 520, in common_checks_context
    cell_source_map = json.load(cell_source_map_fp)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 25: ordinal not in range(128)
```
``` 
input = 
b'{\n    "grants/0/Recipient\xc2\xa0Org/Location/Name": [\n        [\n            "360GivingNov21",\n            "N",\n            2,\n            "Recipient\xc2\xa0Org:Location:Name"\n        ]\n    ],\n    "grants/0/amountAwarded": [\n        [\n            "360GivingNov21",\n            "E",\n            2,\n            "Amount Awarded"\n        ]\n    ],\n    "grants/0/awardDate": [\n        [\n            "360GivingNov21",\n            "F",\n            2,\n            "Award Date"\n        ]\n    ]...
```

https://sentry.io/organizations/open-data-services/issues/2796960637/?project=46181
planio 32086

**Comment by michaelwood** [comment] 2021-11-19 17:54
planio 32086

**Comment by odscjames** [comment] 2021-11-24 10:12
Haven't been able to reproduce locally yet due to other issues bit I have a copy of the file that caused the error (won't post it here tho).

**Comment by odscjames** [comment] 2021-11-24 11:01
Can't reproduce locally by uploading the same file.

Looking at stack track all the code does is: 

```
        with open(
            os.path.join(upload_dir, "cell_source_map.json")
        ) as cell_source_map_fp:
            cell_source_map = json.load(cell_source_map_fp)
```

Can't even reproduce the crash locally - if I download all the files from the server:

```
Python 3.8.12 (default, Sep 10 2021, 00:16:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> 
>>> import json
>>> fp = open('cell_source_map.json')
>>> cell_source_map = json.load(fp)
```

Can't even reproduce the crash on the server - if i become cove user, activate the .ve (I know that should have no affect but I'm getting paranoid at this point) the above Python still works fine.

But the crash is still there - if I re-upload the file to the live server it crashes again.

**Comment by odscjames** [comment] 2021-11-24 11:31
The file does seem to contain c2 at that location so the crash kinda checks out:

    00000010  52 65 63 69 70 69 65 6e  74 c2 a0 4f 72 67 2f 4c  |Recipient..Org/L|

https://bytetool.web.app/en/ascii/code/0xc2/ is the one that causes the crash
https://bytetool.web.app/en/ascii/code/0xa0/ - code after it - also "not in range(128)"
4f-72-67 is "Org" so it's the 2 chars between the words

Puzzled as I _think_ those characters should be set by flatten tool and not anything in the source file, so is it worth looking at what schema file is on the server that is being passed to flatten tool when the cell source map is generated?


Also for ruling things out:

I wondered if uWSGI env different from Python dev server with respect to localles somehow? The only locale thing in uWSGI conf didn't help, this still worked on my laptop:

    LANG=en_US.utf8 ./cove/manage.py runserver



ps. https://dataquality.threesixtygiving.org/data/f78dc8f1-4c70-4034-b5e0-b5694c653912 is my upload that crashes BTW

**Comment by odscjames** [comment] 2021-11-24 11:52
Struck out section in last comment because I'm now pretty sure I'm wrong about that.

I can make a minimal file by copying and pasting the faulty header from the broken file and putting it through live cove - crash. Edit the  file - replace the NBSP (c2 a0) with a real space - save it and reupload - it works. So it's a NBSP in the original file header that makes it crash. 

But I'm not clear why it crashes on live but not on dev and not when just loading in Python. Next I'll look into UWSGI and see if that is running Python with odd locale settings.

But also we can give guidance to the original user now on how to fix their problem manually.

**Comment by odscjames** [comment] 2021-11-24 14:17
Deployed to virtual machine with same salt as live, duplicated error. I can fix it by changing .ve/lib/python3.8/site-packages/libcove/lib/common.py to:

```
        with open(
            os.path.join(upload_dir, "cell_source_map.json")
            , encoding='utf-8'
        ) as cell_source_map_fp:
            cell_source_map = json.load(cell_source_map_fp)

        with open(
            os.path.join(upload_dir, "heading_source_map.json")
                        , encoding='utf-8'

        ) as heading_source_map_fp:
            heading_source_map = json.load(heading_source_map_fp)
```

But am unkeen to suggest that as a fix to the crashes.

**Comment by odscjames** [comment] 2021-11-24 14:37
Done pull request with uwsgi changes:

```
env = LANG=en_US.utf8
env = LANGUAGE=en_US.UTF-8
env = LC_ALL=en_US.UTF-8
```

Also make sure en_US.UTF-8 is actually installed on the server

**Comment by odscjames** [comment] 2021-11-24 14:39
![](https://github.trello.services/images/mini-trello-icon.png) [exception caused by certain chars in data](https://trello.com/c/cJ5Qb85r/226-exception-caused-by-certain-chars-in-data)

**Comment by odscjames** [comment] 2021-11-25 11:47
The crash is now fixed and live.

I have deleted the data for the 2 UID's listed in this ticket to avoid accidental data leakage.

Will open another ticket for a data quality issue.

**Closed by odscjames** 2021-11-25 11:47 UTC
Labels: cove
